project:
  output-dir: book

book:
  output-file: "Thinking-in-R-BW"

format:
  pdf:
    highlight-style: monochrome
    code-block-bg: "#eeeeee"
    include-in-header:
      - preamble.tex
      - bw-preamble.tex
