{
  "hash": "6092f0ba169df04dcef2c1b2bbad4718",
  "result": {
    "engine": "knitr",
    "markdown": "# Data transformation {#sec-data-transformation}\n\n\n\nAre Gentoo penguins heavier than Adelie penguins? The `penguins` data has the answer, but getting there means filtering rows, picking columns, computing a mean, and grouping by species. Every data analysis you will ever write is some arrangement of those same moves, and the question that shapes this chapter is: what is the smallest set of operations that covers all of them?\n\n\n## The idea: verbs for data {#sec-verbs-for-data}\n\nA dplyr\\index{dplyr (package)} verb takes a data frame and returns a data frame: it goes in first, comes out the same shape, and nothing else changes. Five verbs cover most of what you need:\n\n- `filter()`\\index{filter()} keeps rows that match a condition.\n- `select()`\\index{select()} picks columns by name.\n- `mutate()`\\index{mutate()} adds new columns computed from existing ones.\n- `summarise()`\\index{summarise()} collapses rows into a summary.\n- `arrange()`\\index{arrange()} reorders rows.\n\nYou compose them for complex transformations (via pipes, @sec-pipes-and-composition), but each one does exactly one thing.\n\nThese verbs did not come from nowhere. Edgar Codd's 1970 paper defined a *relational algebra*\\index{relational algebra}: a small set of operations on tables where every operation takes a table in and returns a table out, among them restriction (keep rows) and projection (keep columns). IBM resisted at first, because it had a competing database product called IMS. The composability was too useful, and by the 1980s relational databases had won.\n\ndplyr is Codd's algebra with friendlier names. The same ideas appear in SQL, pandas, and data.table because the operations are the same; only the syntax differs. `arrange()` is the one exception — ordering has no relational equivalent, but you need it for display.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(palmerpenguins)\n#> Warning: package 'palmerpenguins' was built under R version 4.6.1\n#> \n#> Attaching package: 'palmerpenguins'\n#> The following objects are masked from 'package:datasets':\n#> \n#>     penguins, penguins_raw\nlibrary(dplyr)\n#> \n#> Attaching package: 'dplyr'\n#> The following objects are masked from 'package:stats':\n#> \n#>     filter, lag\n#> The following objects are masked from 'package:base':\n#> \n#>     intersect, setdiff, setequal, union\n```\n:::\n\n\nThe `penguins` data frame (loaded by `palmerpenguins`) has 344 rows and 8 columns: species, island, bill measurements, flipper length, body mass, sex, and year. Every example in this chapter uses it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npenguins\n#> # A tibble: 344 × 8\n#>    species island  bill_length_mm bill_depth_mm flipper_length_mm body_mass_g\n#>    <fct>   <fct>            <dbl>         <dbl>             <int>       <int>\n#>  1 Adelie  Torger…           39.1          18.7               181        3750\n#>  2 Adelie  Torger…           39.5          17.4               186        3800\n#>  3 Adelie  Torger…           40.3          18                 195        3250\n#>  4 Adelie  Torger…           NA            NA                  NA          NA\n#>  5 Adelie  Torger…           36.7          19.3               193        3450\n#>  6 Adelie  Torger…           39.3          20.6               190        3650\n#>  7 Adelie  Torger…           38.9          17.8               181        3625\n#>  8 Adelie  Torger…           39.2          19.6               195        4675\n#>  9 Adelie  Torger…           34.1          18.1               193        3475\n#> 10 Adelie  Torger…           42            20.2               190        4250\n#> # ℹ 334 more rows\n#> # ℹ 2 more variables: sex <fct>, year <int>\n```\n:::\n\n\n\n## `filter()`: keep rows {#sec-filter}\n\nYou have 344 penguins. You only care about the Adelie ones. How do you throw the rest away?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfilter(penguins, species == \"Adelie\")\n#> # A tibble: 152 × 8\n#>    species island  bill_length_mm bill_depth_mm flipper_length_mm body_mass_g\n#>    <fct>   <fct>            <dbl>         <dbl>             <int>       <int>\n#>  1 Adelie  Torger…           39.1          18.7               181        3750\n#>  2 Adelie  Torger…           39.5          17.4               186        3800\n#>  3 Adelie  Torger…           40.3          18                 195        3250\n#>  4 Adelie  Torger…           NA            NA                  NA          NA\n#>  5 Adelie  Torger…           36.7          19.3               193        3450\n#>  6 Adelie  Torger…           39.3          20.6               190        3650\n#>  7 Adelie  Torger…           38.9          17.8               181        3625\n#>  8 Adelie  Torger…           39.2          19.6               195        4675\n#>  9 Adelie  Torger…           34.1          18.1               193        3475\n#> 10 Adelie  Torger…           42            20.2               190        4250\n#> # ℹ 142 more rows\n#> # ℹ 2 more variables: sex <fct>, year <int>\n```\n:::\n\n\nThe logical expression works the same way as in @sec-comparison-operators, but notice that `species` here refers to the column, not to anything in your global environment. dplyr evaluates the expression inside the data frame.\n\nMultiple conditions, separated by commas, are combined with AND:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfilter(penguins, species == \"Adelie\", body_mass_g > 4000)\n```\n:::\n\n\nThis keeps only Adelie penguins heavier than 4000 grams. You can also write `&` explicitly, but the comma is cleaner.\n\nFor OR, use `|`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfilter(penguins, species == \"Adelie\" | species == \"Chinstrap\")\n```\n:::\n\n\nWhen testing membership in a set, `%in%` is clearer than chaining `|`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfilter(penguins, species %in% c(\"Adelie\", \"Chinstrap\"))\n```\n:::\n\n\nOne detail worth knowing: `filter()` drops rows where the condition evaluates to `NA`. If `body_mass_g` is `NA` for a row, then `body_mass_g > 4000` is `NA`, and `filter()` excludes it. This is usually what you want, but if you need to keep `NA` rows, test for them explicitly: `filter(penguins, is.na(body_mass_g))`.\n\nUnder the hood, `filter()` is doing the same logical subsetting from @sec-comparison-operators: `penguins[penguins$species == \"Adelie\", ]`. The verb makes the intent explicit and, more importantly, composable with other verbs. But keeping rows is only half the story; what about columns you don't need?\n\n\n### Exercises {.unnumbered}\n\n1. Filter `penguins` to keep only female penguins from Biscoe island.\n2. Filter `penguins` to keep rows where `flipper_length_mm` is greater than 200 or `body_mass_g` is less than 3000.\n3. How many rows have missing values in `sex`? Use `filter()` and `nrow()`.\n\n\n## `select()`: pick columns {#sec-select}\n\nEight columns is manageable. Eighty is not. When you only need species, bill length, and body mass, carrying around five extra columns clutters every printout, slows every join, and obscures what matters. `select()` strips a data frame down to the columns you name.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nselect(penguins, species, bill_length_mm, body_mass_g)\n#> # A tibble: 344 × 3\n#>    species bill_length_mm body_mass_g\n#>    <fct>            <dbl>       <int>\n#>  1 Adelie            39.1        3750\n#>  2 Adelie            39.5        3800\n#>  3 Adelie            40.3        3250\n#>  4 Adelie            NA            NA\n#>  5 Adelie            36.7        3450\n#>  6 Adelie            39.3        3650\n#>  7 Adelie            38.9        3625\n#>  8 Adelie            39.2        4675\n#>  9 Adelie            34.1        3475\n#> 10 Adelie            42          4250\n#> # ℹ 334 more rows\n```\n:::\n\n\nThe rest are gone.\n\nDrop columns by prefixing with `-`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nselect(penguins, -year)\n```\n:::\n\n\nFor more flexible selection, dplyr provides helper functions. `starts_with()`, `ends_with()`, and `contains()` match column names by pattern:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nselect(penguins, starts_with(\"bill\"))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nselect(penguins, ends_with(\"mm\"))\n```\n:::\n\n\n`where()` selects columns based on their content, not their name. `where(is.numeric)` keeps every numeric column:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nselect(penguins, species, where(is.numeric))\n```\n:::\n\n\nYou can rename columns inside `select()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nselect(penguins, species, mass = body_mass_g)\n#> # A tibble: 344 × 2\n#>    species  mass\n#>    <fct>   <int>\n#>  1 Adelie   3750\n#>  2 Adelie   3800\n#>  3 Adelie   3250\n#>  4 Adelie     NA\n#>  5 Adelie   3450\n#>  6 Adelie   3650\n#>  7 Adelie   3625\n#>  8 Adelie   4675\n#>  9 Adelie   3475\n#> 10 Adelie   4250\n#> # ℹ 334 more rows\n```\n:::\n\n\nThis selects `species` and `body_mass_g`, renaming the latter to `mass`. But notice what happened: every other column is gone. Renaming inside `select()` is really selection-with-renaming, not renaming-with-selection. If you want a new name but need the other six columns to survive, you have to decide: do you list every column you want to keep, or do you use a different verb entirely? That trade-off between concision and preservation comes up constantly.\n\nIf you want to rename without dropping columns, use `rename()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrename(penguins, mass = body_mass_g)\n```\n:::\n\n\nTo reorder columns (move `species` to the front, keep everything else), use `everything()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nselect(penguins, island, species, everything())\n```\n:::\n\n\n\n### Exercises {.unnumbered}\n\n1. Select all columns from `penguins` that contain the string `\"length\"`.\n2. Select `species`, `island`, and all numeric columns. (Hint: combine names and `where()`.)\n3. What is the difference between `select(penguins, mass = body_mass_g)` and `rename(penguins, mass = body_mass_g)`? Try both.\n\n\n## `mutate()`: compute new columns {#sec-mutate}\n\nBody mass is recorded in grams, but your collaborator's model expects kilograms.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmutate(penguins, mass_kg = body_mass_g / 1000)\n#> # A tibble: 344 × 9\n#>    species island  bill_length_mm bill_depth_mm flipper_length_mm body_mass_g\n#>    <fct>   <fct>            <dbl>         <dbl>             <int>       <int>\n#>  1 Adelie  Torger…           39.1          18.7               181        3750\n#>  2 Adelie  Torger…           39.5          17.4               186        3800\n#>  3 Adelie  Torger…           40.3          18                 195        3250\n#>  4 Adelie  Torger…           NA            NA                  NA          NA\n#>  5 Adelie  Torger…           36.7          19.3               193        3450\n#>  6 Adelie  Torger…           39.3          20.6               190        3650\n#>  7 Adelie  Torger…           38.9          17.8               181        3625\n#>  8 Adelie  Torger…           39.2          19.6               195        4675\n#>  9 Adelie  Torger…           34.1          18.1               193        3475\n#> 10 Adelie  Torger…           42            20.2               190        4250\n#> # ℹ 334 more rows\n#> # ℹ 3 more variables: sex <fct>, year <int>, mass_kg <dbl>\n```\n:::\n\n\nYou can reference a column you just created in the same `mutate()` call:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmutate(\n  penguins,\n  mass_kg = body_mass_g / 1000,\n  mass_lb = mass_kg * 2.205\n)\n```\n:::\n\n\n`mass_lb` uses `mass_kg`, which was defined one line above; dplyr evaluates them in order, top to bottom. This is actually surprising. R normally evaluates function arguments independently of each other. If you called a plain function with two arguments, the second could not refer to the first. `mutate()` breaks that expectation: it processes columns sequentially, so each expression can see everything defined above it. Reverse the order and `mass_lb` would fail, because `mass_kg` would not exist yet.\n\nAny function that works on vectors works inside `mutate()`: `log()`, `sqrt()`, `cumsum()`, `lag()`, `lead()`, `percent_rank()`. The conditional functions from @sec-vectorized-conditionals work here too:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmutate(\n  penguins,\n  size = if_else(body_mass_g > 4000, \"large\", \"small\")\n)\n```\n:::\n\n\nFor more than two categories, `case_when()` is the tool:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmutate(\n  penguins,\n  size = case_when(\n    body_mass_g > 5000 ~ \"large\",\n    body_mass_g > 3500 ~ \"medium\",\n    .default = \"small\"\n  )\n)\n```\n:::\n\n\nIf you want to keep only the new columns and drop everything else, use `.keep = \"none\"`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmutate(\n  penguins,\n  mass_kg = body_mass_g / 1000,\n  .keep = \"none\"\n)\n#> # A tibble: 344 × 1\n#>    mass_kg\n#>      <dbl>\n#>  1    3.75\n#>  2    3.8 \n#>  3    3.25\n#>  4   NA   \n#>  5    3.45\n#>  6    3.65\n#>  7    3.62\n#>  8    4.68\n#>  9    3.48\n#> 10    4.25\n#> # ℹ 334 more rows\n```\n:::\n\n\n\n### Exercises {.unnumbered}\n\n1. Add a column `bill_ratio` that divides `bill_length_mm` by `bill_depth_mm`.\n2. Use `mutate()` and `case_when()` to create a column `island_code` that maps `\"Biscoe\"` to `\"B\"`, `\"Dream\"` to `\"D\"`, and `\"Torgersen\"` to `\"T\"`.\n3. What happens if you use a column name that already exists in `mutate()`? Try `mutate(penguins, species = toupper(species))`.\n\n\n## `summarise()` and `group_by()`: aggregate {#sec-summarise-group-by}\n\nWhat is the average body mass of a penguin in this dataset?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummarise(penguins, mean_mass = mean(body_mass_g, na.rm = TRUE))\n#> # A tibble: 1 × 1\n#>   mean_mass\n#>       <dbl>\n#> 1     4202.\n```\n:::\n\n\nOne row. One number. On its own, collapsing everything into a single summary is limited. The interesting question is not \"what is the mean?\" but \"how does the mean differ across species?\" That is where `group_by()` enters.\n\n`group_by()`\\index{group\\_by()} marks a data frame as grouped. It doesn't change the data; it attaches metadata that tells subsequent verbs to operate per group:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npenguins_grouped <- group_by(penguins, species)\nsummarise(penguins_grouped, mean_mass = mean(body_mass_g, na.rm = TRUE))\n#> # A tibble: 3 × 2\n#>   species   mean_mass\n#>   <fct>         <dbl>\n#> 1 Adelie        3701.\n#> 2 Chinstrap     3733.\n#> 3 Gentoo        5076.\n```\n:::\n\n\n`summarise()` applied `mean()` within each group and returned one row per species.\n\nCompare the two calls. Without `group_by()`, `summarise()` collapsed everything into a single row — one mean, one answer. With `group_by(species)`, the same verb produced three rows, one per species, without any change to the `summarise()` call itself. The column you group by acts as a partitioning function: it splits the data into subsets, and `summarise()` runs independently inside each one\\index{split-apply-combine}.\n\n::: {.callout-note collapse=\"true\"}\n## Grouping in other languages\n\nSQL spells this `GROUP BY`; Spark uses explicit partitioning; in functional programming the same idea appears as `foldByKey`, where a reduce operation runs per partition rather than globally. The underlying pattern — an aggregation function paired with a partitioning structure — is the same across all of them.\n:::\n\nWhat makes dplyr's version distinctive is that the partition is invisible metadata attached to the data frame — `group_by()` changes nothing you can see in a printout, but it changes everything `summarise()` does. That silent metadata is powerful, and it is also the source of the most common grouping bugs.\n\nYou can group by multiple variables:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummarise(\n  group_by(penguins, species, island),\n  mean_mass = mean(body_mass_g, na.rm = TRUE),\n  count = n()\n)\n#> `summarise()` has regrouped the output.\n#> ℹ Summaries were computed grouped by species and island.\n#> ℹ Output is grouped by species.\n#> ℹ Use `summarise(.groups = \"drop_last\")` to silence this message.\n#> ℹ Use `summarise(.by = c(species, island))` for per-operation grouping\n#>   (`?dplyr::dplyr_by`) instead.\n#> # A tibble: 5 × 4\n#> # Groups:   species [3]\n#>   species   island    mean_mass count\n#>   <fct>     <fct>         <dbl> <int>\n#> 1 Adelie    Biscoe        3710.    44\n#> 2 Adelie    Dream         3688.    56\n#> 3 Adelie    Torgersen     3706.    52\n#> 4 Chinstrap Dream         3733.    68\n#> 5 Gentoo    Biscoe        5076.   124\n```\n:::\n\n\n`n()`\\index{n()} counts the number of rows in each group; `n_distinct()` counts unique values:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummarise(\n  group_by(penguins, species),\n  n_islands = n_distinct(island)\n)\n#> # A tibble: 3 × 2\n#>   species   n_islands\n#>   <fct>         <int>\n#> 1 Adelie            3\n#> 2 Chinstrap         1\n#> 3 Gentoo            1\n```\n:::\n\n\nThe shortcut `count()`\\index{count()} does `group_by()` plus `summarise(n = n())` in one step:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncount(penguins, species)\n#> # A tibble: 3 × 2\n#>   species       n\n#>   <fct>     <int>\n#> 1 Adelie      152\n#> 2 Chinstrap    68\n#> 3 Gentoo      124\n```\n:::\n\n\n::: callout-tip\n## Opinion\nAfter `summarise()`, the last grouping variable is silently peeled off, which means the result may still be grouped. A `mutate()` you expect to operate on the full data frame then operates per group instead. Add `.groups = \"drop\"` to `summarise()`, or call `ungroup()` afterward.\n:::\n\n\n### Exercises {.unnumbered}\n\n1. Compute the median `flipper_length_mm` for each species.\n2. Use `group_by()` and `summarise()` to find the maximum `bill_length_mm` per species and island combination.\n3. Use `count()` to find how many penguins were observed in each year.\n\n\n\n## `arrange()`: order rows {#sec-arrange}\n\n`arrange()` sorts rows. The default is ascending:\n\n\n::: {.cell}\n\n```{.r .cell-code}\narrange(penguins, body_mass_g)\n#> # A tibble: 344 × 8\n#>    species  island bill_length_mm bill_depth_mm flipper_length_mm body_mass_g\n#>    <fct>    <fct>           <dbl>         <dbl>             <int>       <int>\n#>  1 Chinstr… Dream            46.9          16.6               192        2700\n#>  2 Adelie   Biscoe           36.5          16.6               181        2850\n#>  3 Adelie   Biscoe           36.4          17.1               184        2850\n#>  4 Adelie   Biscoe           34.5          18.1               187        2900\n#>  5 Adelie   Dream            33.1          16.1               178        2900\n#>  6 Adelie   Torge…           38.6          17                 188        2900\n#>  7 Chinstr… Dream            43.2          16.6               187        2900\n#>  8 Adelie   Biscoe           37.9          18.6               193        2925\n#>  9 Adelie   Dream            37.5          18.9               179        2975\n#> 10 Adelie   Dream            37            16.9               185        3000\n#> # ℹ 334 more rows\n#> # ℹ 2 more variables: sex <fct>, year <int>\n```\n:::\n\n\nWrap a column in `desc()` for descending order:\n\n\n::: {.cell}\n\n```{.r .cell-code}\narrange(penguins, desc(body_mass_g))\n```\n:::\n\n\nMultiple columns break ties; sort by species alphabetically, then by mass descending within each species:\n\n\n::: {.cell}\n\n```{.r .cell-code}\narrange(penguins, species, desc(body_mass_g))\n```\n:::\n\n\nUnlike the other verbs, `arrange()` ignores grouping by default. If you want to sort within groups, set `.by_group = TRUE`.\n\n`arrange()` is pure display. No information is added or removed, only the order of rows changes. But a well-sorted table can reveal patterns that a jumbled one hides, and sometimes the five core verbs are not quite enough to expose them.\n\n\n## More verbs {#sec-more-verbs}\n\n`distinct()` returns unique rows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndistinct(penguins, species, island)\n#> # A tibble: 5 × 2\n#>   species   island   \n#>   <fct>     <fct>    \n#> 1 Adelie    Torgersen\n#> 2 Adelie    Biscoe   \n#> 3 Adelie    Dream    \n#> 4 Gentoo    Biscoe   \n#> 5 Chinstrap Dream\n```\n:::\n\n\nSeven combinations of species and island exist in the data.\n\n`slice_head()`\\index{slice()} and `slice_tail()` keep the first or last `n` rows:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nslice_head(penguins, n = 3)\n#> # A tibble: 3 × 8\n#>   species island   bill_length_mm bill_depth_mm flipper_length_mm body_mass_g\n#>   <fct>   <fct>             <dbl>         <dbl>             <int>       <int>\n#> 1 Adelie  Torgers…           39.1          18.7               181        3750\n#> 2 Adelie  Torgers…           39.5          17.4               186        3800\n#> 3 Adelie  Torgers…           40.3          18                 195        3250\n#> # ℹ 2 more variables: sex <fct>, year <int>\n```\n:::\n\n\n`slice_max()` and `slice_min()` keep the rows with the largest or smallest values:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nslice_max(penguins, body_mass_g, n = 3)\n#> # A tibble: 4 × 8\n#>   species island bill_length_mm bill_depth_mm flipper_length_mm body_mass_g\n#>   <fct>   <fct>           <dbl>         <dbl>             <int>       <int>\n#> 1 Gentoo  Biscoe           49.2          15.2               221        6300\n#> 2 Gentoo  Biscoe           59.6          17                 230        6050\n#> 3 Gentoo  Biscoe           51.1          16.3               220        6000\n#> 4 Gentoo  Biscoe           48.8          16.2               222        6000\n#> # ℹ 2 more variables: sex <fct>, year <int>\n```\n:::\n\n\n`pull()` extracts a single column as a vector, the pipe-friendly equivalent of `$`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npull(penguins, species) |> head()\n#> [1] Adelie Adelie Adelie Adelie Adelie Adelie\n#> Levels: Adelie Chinstrap Gentoo\n```\n:::\n\n\n`relocate()` moves columns without dropping any. Move `sex` and `year` to the front:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrelocate(penguins, sex, year)\n```\n:::\n\n\nFinally, `across()`\\index{across()} applies a function to multiple columns at once. Summarise all numeric columns by their mean:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummarise(penguins, across(where(is.numeric), \\(x) mean(x, na.rm = TRUE)))\n#> # A tibble: 1 × 5\n#>   bill_length_mm bill_depth_mm flipper_length_mm body_mass_g  year\n#>            <dbl>         <dbl>             <dbl>       <dbl> <dbl>\n#> 1           43.9          17.2              201.       4202. 2008.\n```\n:::\n\n\n`across()` works inside `mutate()` too. Round every numeric column to one decimal place:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmutate(penguins, across(where(is.numeric), \\(x) round(x, 1)))\n```\n:::\n\n\n`across()` pairs naturally with `where()`, `starts_with()`, and the other selection helpers from @sec-select. @sec-iteration-without-loops generalizes the same idea (apply a function to each element of a collection) beyond data frames. But before you build elaborate pipelines out of these verbs, it is worth seeing what they look like without dplyr at all.\n\n\n### Exercises {.unnumbered}\n\n1. Use `distinct()` to find all unique values of `island`.\n2. Use `slice_max()` to find the 5 penguins with the longest flippers.\n3. Use `across()` inside `summarise()` to compute the standard deviation (`sd()`) of every numeric column, grouped by species.\n\n\n\n## The base R equivalents {#sec-base-r-equivalents}\n\nEverything dplyr does, base R can do too. The verbs are convenient wrappers, not new capabilities. So what exactly do you gain?\n\n`filter()` is logical subsetting:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# dplyr\nfilter(penguins, species == \"Adelie\", body_mass_g > 4000)\n\n# base R\npenguins[penguins$species == \"Adelie\" & penguins$body_mass_g > 4000, ]\n```\n:::\n\n\n`select()` is column indexing:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# dplyr\nselect(penguins, species, body_mass_g)\n\n# base R\npenguins[, c(\"species\", \"body_mass_g\")]\n```\n:::\n\n\n`mutate()` is direct assignment:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# dplyr\nmutate(penguins, mass_kg = body_mass_g / 1000)\n\n# base R\npenguins$mass_kg <- penguins$body_mass_g / 1000\n```\n:::\n\n\nThe base R version modifies the binding; the dplyr version returns a new data frame and leaves the original untouched. This distinction matters more as pipelines grow longer.\n\n`summarise()` plus `group_by()` maps to `aggregate()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# dplyr\nsummarise(group_by(penguins, species), mean_mass = mean(body_mass_g, na.rm = TRUE))\n\n# base R\naggregate(body_mass_g ~ species, data = penguins, FUN = mean, na.rm = TRUE)\n```\n:::\n\n\n`arrange()` is `order()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# dplyr\narrange(penguins, desc(body_mass_g))\n\n# base R\npenguins[order(-penguins$body_mass_g), ]\n```\n:::\n\n\nBase R also has `subset()`, which combines filtering and column selection:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsubset(penguins, species == \"Adelie\", select = c(species, body_mass_g))\n```\n:::\n\n\n`subset()` is clean and readable; for simple operations, it works well. Where dplyr pulls ahead is composability: every verb takes a data frame and returns one, so you can chain them. Base R's equivalents each return something slightly different: `aggregate()` renames your columns, `order()` gives you indices instead of a data frame. So you spend time wiring them together instead of thinking about your data.\n\ndplyr and SQL\\index{SQL} are the same language wearing different syntax. Both implement relational algebra, which is why they feel similar:\n\n| dplyr | SQL |\n|---|---|\n| `filter(penguins, species == \"Adelie\")` | `SELECT * FROM penguins WHERE species = 'Adelie'` |\n| `group_by(species) |> summarise(n = n())` | `SELECT species, COUNT(*) AS n ... GROUP BY species` |\n\nCall `show_query()` on a database-backed tibble to see the translation directly.\n\n::: {.callout-note collapse=\"true\"}\n## Verb composition is a monoid\n\nA dplyr pipeline is function composition: each verb transforms a data frame and passes it to the next, the same composition from lambda calculus, (g ∘ f)(x) = g(f(x)), applied to tables instead of numbers. This is the same monoid pattern from @sec-no-scalars: an associative operation (verb composition) with an identity element (a verb that returns the data frame unchanged). Compose any sequence of dplyr verbs and the result is still a data frame.\n:::\n\n::: callout-tip\n## Opinion\nLearn the base R equivalents. You will encounter them in other people's code, in Stack Overflow answers, in older packages. But write dplyr in your own work, because the verbs compose, the names communicate intent, and the argument order is consistent. When you read `filter(penguins, species == \"Adelie\")`, the operation is the function name. When you read `penguins[penguins$species == \"Adelie\", ]`, you have to parse the indexing to understand what's happening. That parsing cost, multiplied across every line of a script, is exactly the kind of friction Codd's algebra was designed to remove.\n:::\n\nNow you have every verb you need to answer the question from the start of the chapter:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npenguins |>\n  filter(!is.na(body_mass_g)) |>\n  group_by(species) |>\n  summarise(mean_mass = mean(body_mass_g))\n#> # A tibble: 3 × 2\n#>   species   mean_mass\n#>   <fct>         <dbl>\n#> 1 Adelie        3701.\n#> 2 Chinstrap     3733.\n#> 3 Gentoo        5076.\n```\n:::\n\n\nGentoo penguins average roughly 5,076 grams; Adelie average 3,706. The answer was always in the data. Getting to it required four verbs and five lines.\n\n\n### Exercises {.unnumbered}\n\n1. Rewrite `select(penguins, species, island, body_mass_g)` using base R bracket notation.\n2. Rewrite `arrange(penguins, bill_length_mm)` using `order()`.\n3. Use `aggregate()` to compute the mean `flipper_length_mm` per island. Compare with the `group_by()` plus `summarise()` version.\n",
    "supporting": [
      "ch14-data-transformation_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}